<?php
/**
 * Seed Team Members Import
 *
 * One-time import script that creates Employee posts from the old e3_team data.
 * Trigger: visit any WP page with ?e3_seed_team=1 while logged in as admin.
 *
 * After running, this script can be safely removed or left dormant.
 */

if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

add_action( 'admin_init', 'e3_seed_team_members' );
function e3_seed_team_members() {
    if ( empty( $_GET['e3_seed_team'] ) || $_GET['e3_seed_team'] !== '1' ) {
        return;
    }

    if ( ! current_user_can( 'manage_options' ) ) {
        wp_die( 'Unauthorized' );
    }

    // Prevent timeout on large imports
    set_time_limit( 300 );

    $team_members = e3_get_team_data();

    $created  = 0;
    $skipped  = 0;
    $errors   = array();

    foreach ( $team_members as $member ) {
        $slug = sanitize_title( $member['slug'] );

        // Skip if already exists
        $existing = get_posts( array(
            'post_type'   => 'employees',
            'name'        => $slug,
            'post_status' => array( 'publish', 'draft', 'private', 'pending' ),
            'numberposts' => 1,
        ) );

        if ( ! empty( $existing ) ) {
            $skipped++;
            continue;
        }

        // Create the post
        $post_id = wp_insert_post( array(
            'post_type'    => 'employees',
            'post_title'   => $member['title'],
            'post_content' => $member['content'],
            'post_name'    => $slug,
            'post_status'  => $member['status'],
            'menu_order'   => intval( $member['order'] ),
        ), true );

        if ( is_wp_error( $post_id ) ) {
            $errors[] = $member['title'] . ': ' . $post_id->get_error_message();
            continue;
        }

        // Set meta fields
        if ( ! empty( $member['job_title'] ) ) {
            update_post_meta( $post_id, '_e3_employee_role', sanitize_text_field( $member['job_title'] ) );
        }
        if ( ! empty( $member['division'] ) ) {
            update_post_meta( $post_id, '_e3_employee_division', sanitize_text_field( $member['division'] ) );
        }
        if ( ! empty( $member['tagline'] ) ) {
            update_post_meta( $post_id, '_e3_employee_tagline', sanitize_text_field( $member['tagline'] ) );
        }
        update_post_meta( $post_id, '_e3_employee_order', intval( $member['order'] ) );

        // Download and set featured image
        if ( ! empty( $member['image_url'] ) ) {
            $image_id = e3_sideload_team_image( $member['image_url'], $post_id, $member['title'] );
            if ( $image_id && ! is_wp_error( $image_id ) ) {
                set_post_thumbnail( $post_id, $image_id );
            }
        }

        $created++;
    }

    // Output results
    $total = count( $team_members );
    wp_die(
        "<h2>Team Import Complete</h2>" .
        "<p><strong>Total in CSV:</strong> {$total}</p>" .
        "<p><strong>Created:</strong> {$created}</p>" .
        "<p><strong>Skipped (already exist):</strong> {$skipped}</p>" .
        ( ! empty( $errors ) ? "<p><strong>Errors:</strong><br>" . implode( '<br>', $errors ) . "</p>" : '' ) .
        "<p><a href='" . admin_url( 'edit.php?post_type=employees' ) . "'>View Employees &rarr;</a></p>",
        'Team Import Results',
        array( 'back_link' => true )
    );
}

/**
 * Sideload an image from URL into the media library
 */
function e3_sideload_team_image( $url, $post_id, $desc = '' ) {
    require_once ABSPATH . 'wp-admin/includes/media.php';
    require_once ABSPATH . 'wp-admin/includes/file.php';
    require_once ABSPATH . 'wp-admin/includes/image.php';

    $tmp = download_url( $url );
    if ( is_wp_error( $tmp ) ) {
        return $tmp;
    }

    $file_array = array(
        'name'     => basename( parse_url( $url, PHP_URL_PATH ) ),
        'tmp_name' => $tmp,
    );

    $id = media_handle_sideload( $file_array, $post_id, $desc );

    if ( is_wp_error( $id ) ) {
        @unlink( $tmp );
    }

    return $id;
}

/**
 * All team member data extracted from the CSV export.
 * Each entry has: title, content, slug, status, order, job_title, division, tagline, image_url
 */
function e3_get_team_data() {
    return array(
        array(
            'title'     => 'KLIP',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Klip shaped our culture. He led with heart, built with purpose, and made sure we had fun along the way. Though he\'s no longer steering the ship day to day, his energy still fuels the journey.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'klip-weaver',
            'status'    => 'draft',
            'order'     => 76,
            'job_title' => 'keeping it "all good"',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/K-Weaver.jpg',
        ),
        array(
            'title'     => 'JOSH, PE, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Josh brings decades of experience delivering infrastructure solutions. He leads with clarity, focus, and just enough mischief to keep things interesting.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'josh-combs-pe-cem',
            'status'    => 'publish',
            'order'     => 0,
            'job_title' => 'president',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Josh-Combs-VP-Engineering.jpg',
        ),
        array(
            'title'     => 'MANDAH',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Baking enthusiast here to whip up win-win scenarios while keeping things sweet &amp; fun.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'mandah',
            'status'    => 'publish',
            'order'     => 24,
            'job_title' => 'executive administrator',
            'division'  => 'Business Administration',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Mandah-Wilson-600x450-1.jpg',
        ),
        array(
            'title'     => 'CHALO',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Chalo is passionate about technology, energy savings, and a great steak.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'chalo-valls',
            'status'    => 'publish',
            'order'     => 1,
            'job_title' => 'vice president, technology',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/C-Valls.jpg',
        ),
        array(
            'title'     => 'DANIEL, PE, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Daniel is a part of the best engineering group in the industry and finds solutions for his clients\' issues.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'daniel-meyer-pe-cem',
            'status'    => 'publish',
            'order'     => 2,
            'job_title' => 'vice president, engineering',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/D-Meyer.jpg',
        ),
        array(
            'title'     => 'JEFF',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Jeff loves his family and the western lifestyle they live. Although it requires much from his family, the reward of that effort is great.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jeff-freeman',
            'status'    => 'publish',
            'order'     => 3,
            'job_title' => 'vice president, construction operations',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jeff-Freeman-Project-Manager.jpg',
        ),
        array(
            'title'     => 'DON',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Don was an E3 Founding Father. And, like many dads, Don nurtured E3 from our roots, patiently helped us grow, and then took off for the fishing boat as soon as he knew we could succeed in life.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'don-meek',
            'status'    => 'publish',
            'order'     => 77,
            'job_title' => 'gone fishing',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/D-Meek.jpg',
        ),
        array(
            'title'     => 'CINDY',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Cindy is a control freak…at least when it comes to E3\'s money. Teamwork at E3 makes her job fun and rewarding.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'cindy-cannedy',
            'status'    => 'publish',
            'order'     => 4,
            'job_title' => 'vice president, finance & accounting',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/C-Winget.jpg',
        ),
        array(
            'title'     => 'DEB',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Deb enjoys spending time with her apophyllite collection under the poplars in spring.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'deb-broach-shrm-cp',
            'status'    => 'draft',
            'order'     => 26,
            'job_title' => 'executive administrator',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Deb-Broach-Business-Operations-Manager.jpg',
        ),
        array(
            'title'     => 'JUSTIN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>When Justin isn\'t turning bright ideas into beautiful spaces, he is a veteran, husband and dad, calling audibles on Sundays and reeling in memories the rest of the week.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'justin-denton',
            'status'    => 'publish',
            'order'     => 64,
            'job_title' => 'lighting project manager',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2022/05/Justin-Denton-600x450-1.jpg',
        ),
        array(
            'title'     => 'JASON, MFA',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>As a storyteller, Jason loves a good yarn. He especially likes untangling the knots.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jason-flowers-mfa',
            'status'    => 'publish',
            'order'     => 6,
            'job_title' => 'director of marketing',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jason-Flowers-057.jpg',
        ),
        array(
            'title'     => 'GREG',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Greg was given the task of writing a bio. He quickly discovered his inability to process simple tasks without the aid of Excel and light fixtures.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'greg-reinke',
            'status'    => 'publish',
            'order'     => 10,
            'job_title' => 'director of E3 lighting',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/G-Reinke.jpg',
        ),
        array(
            'title'     => 'STEVE, PE, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>With 30+ years in the energy efficiency business, Steve is passionate about collecting energy savings for clients. He is also passionate about collecting rocks and fossils in his spare time.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'steve-schliesing',
            'status'    => 'publish',
            'order'     => 11,
            'job_title' => 'director of engineering',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Steve-Schliesing-1.jpg',
        ),
        array(
            'title'     => 'BRIAN, PE, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Brian is a process innovator, Excel master, and energy detective. He\'s been developing sustainable energy savings projects since Aikman won his last Super Bowl. His daughters are his greatest treasure.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'brian-bash-pe-cem',
            'status'    => 'publish',
            'order'     => 12,
            'job_title' => 'director of engineering',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Brian-Bash-Web.jpg',
        ),
        array(
            'title'     => 'DONALD',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Donald loves making buildings work, clients happy, and saving energy almost as much as he loves catching Crappie and Red Fish.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'donald-todd',
            'status'    => 'publish',
            'order'     => 15,
            'job_title' => 'director of construction operations, southwest',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/D-Todd.jpg',
        ),
        array(
            'title'     => 'ERIC, PMP',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Eric is no longer fairly confident he would win an E3 dance competition. Good moves managing projects have also won his clients\' confidence.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'eric-meek-pmp',
            'status'    => 'publish',
            'order'     => 17,
            'job_title' => 'director of construction operations, north',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/E-Meek.jpg',
        ),
        array(
            'title'     => 'JASON',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>From Navy rescue swimmer to helicopter pilot, master electrician to homesteader, Jason brings true Renaissance Man energy to every project.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jason-walding',
            'status'    => 'publish',
            'order'     => 74,
            'job_title' => 'senior project manager',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jason-Walding-074.jpg',
        ),
        array(
            'title'     => 'JEFF',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Jeff enjoys helping clients better understand and operate their buildings\' mechanical systems almost as much as soliciting giggles and grins from his new grand baby.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jeff-cooke',
            'status'    => 'draft',
            'order'     => 18,
            'job_title' => 'retro-commissioning manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jeff-Cooke-Retro-Commissioning-Manager.jpg',
        ),
        array(
            'title'     => 'PATRICIA',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Pat is often the first face seen and the voice most often heard with multi-tasking as her middle name.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'patricia-thompson',
            'status'    => 'publish',
            'order'     => 20,
            'job_title' => 'business operations specialist',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/P-Thompson.jpg',
        ),
        array(
            'title'     => 'LUISA',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Luisa is happy when she has a place for everything and everything is in its place.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'luisa-valls',
            'status'    => 'publish',
            'order'     => 47,
            'job_title' => 'business development administrator',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Luisa-Valls.jpg',
        ),
        array(
            'title'     => 'JANA',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Don\'t let those Weaver boys fool you. It\'s only all good when mama says it\'s all good, cause everybody knows, when momma ain\'t happy, ain\'t nobody happy.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jana-weaver',
            'status'    => 'draft',
            'order'     => 27,
            'job_title' => 'sales administrator',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jana-Weaver.jpg',
        ),
        array(
            'title'     => 'COLIN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>After the numbers are crunched, Colin enjoys spending time with his beautiful wife, playing hockey and cuddling up with his little black cat.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'colin-stevic',
            'status'    => 'publish',
            'order'     => 28,
            'job_title' => 'senior accountant',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Colin-600x450-1.jpg',
        ),
        array(
            'title'     => 'ADAM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Adam is always smiling and is extremely proud of his family. If you tell Adam not to talk to strangers, his wife will say "he\'s never met one!"</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'adam-anders',
            'status'    => 'publish',
            'order'     => 32,
            'job_title' => 'business development',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Adam-Anders-120.jpg',
        ),
        array(
            'title'     => 'LANCE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Lance loves helping his clients achieve their vision. He adores his family and the time he spends with them, whether traveling or introducing his grandkids to the traditions of Texas A&M at football games.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'lance-wyatt',
            'status'    => 'publish',
            'order'     => 34,
            'job_title' => 'business development',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/LanceTake2-160.jpg',
        ),
        array(
            'title'     => 'BILL',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Bill is most proud of his beautiful family. \'All this time we didn\'t realize we were making memories, we just knew we were having fun!\'</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'bill-savarino',
            'status'    => 'publish',
            'order'     => 33,
            'job_title' => 'business development',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/B-Savarino.jpg',
        ),
        array(
            'title'     => 'MIKE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Mike enjoys the challenge of endurance sports and helping clients accomplish their goals. Sometimes those are one in the same.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'mike-cothran',
            'status'    => 'publish',
            'order'     => 35,
            'job_title' => 'business development',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Mike-Cothran-1.jpg',
        ),
        array(
            'title'     => 'JARED, LEED AP',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Jared is a wannabe triathlete that can swim, but runs with two left feet. He loves wasting his energy racing while saving his clients\' energy.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jared-mccurley-leed-ap',
            'status'    => 'publish',
            'order'     => 5,
            'job_title' => 'vice president, business development',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/J-McCurley.jpg',
        ),
        array(
            'title'     => 'VINCE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Vince always finds time for his family, solutions for his clients, and the closest Whataburger.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'vince-zubicek',
            'status'    => 'publish',
            'order'     => 30,
            'job_title' => 'business development team lead',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/V-Zubicek.jpg',
        ),
        array(
            'title'     => 'JAKE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>It\'s all good if dad says it is.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jake-weaver',
            'status'    => 'draft',
            'order'     => 7,
            'job_title' => 'strategic partnerships and marketing manager',
            'division'  => 'Marketing, Communications & Media',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/J-Weaver.jpg',
        ),
        array(
            'title'     => 'STEVEN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Steven loves helping others achieve success. When he\'s not focusing on client goals, his goal is to spend as much time on the lake with his family as possible.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'steven-monkres',
            'status'    => 'publish',
            'order'     => 36,
            'job_title' => 'business development',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Steven-Monkres-600-x-450.jpg',
        ),
        array(
            'title'     => 'JASON',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>After 12 years as a county elected official, Jason loves talking local government and helping solve problems. Especially when he can do both at the same time.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jason-brinkley',
            'status'    => 'draft',
            'order'     => 41,
            'job_title' => 'business development, county',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jason-Brinkley.jpg',
        ),
        array(
            'title'     => 'DENNIS',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Dennis honored God with his life, a beautiful love for his wife and children, a passion for treating people with honor and respect, and a desire to be the very best at all he did. Dennis was one of the best and we miss him dearly.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'dennis-bennett',
            'status'    => 'publish',
            'order'     => 46,
            'job_title' => 'always in our hearts',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/D-Bennett.jpg',
        ),
        array(
            'title'     => 'KEVEN, PE, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>The extra "E" in Keven\'s name is for the added effort he demonstrates in developing effective projects and efficiency improvements for clients.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'keven-bridges-pe-cem',
            'status'    => 'publish',
            'order'     => 48,
            'job_title' => 'senior MEP engineer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/K-Bridges.jpg',
        ),
        array(
            'title'     => 'SEBASTIAN, PE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Sebastian is a detail-oriented engineer and takes pride in providing quality solutions. When he is not working, Sebastian loves spending time outside hiking, biking, and paddle boarding with his family.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'sebastian-olivera-pe',
            'status'    => 'publish',
            'order'     => 55,
            'job_title' => 'senior MEP engineer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Sebastian-Olivera-096.jpg',
        ),
        array(
            'title'     => 'KENT, PE, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Kent thrives on developing creative solutions for clients\' energy problems. When not doing that, he enjoys time with family as well as playing hockey and volleyball.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'kent-rothbauer-pe-cem',
            'status'    => 'draft',
            'order'     => 50,
            'job_title' => 'senior project engineer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Kent-Rothbauer-1.jpg',
        ),
        array(
            'title'     => 'JIM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>When Jim isn\'t processing or analyzing data, he is an avid player of board and card games, which requires processing and analyzing data.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jim-ingram',
            'status'    => 'publish',
            'order'     => 58,
            'job_title' => 'engineering administrator',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/J-Ingram.jpg',
        ),
        array(
            'title'     => 'JUSTIN, PE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Justin knows HVAC. He\'s been an installer, a technician, and a designer since graduating from Mississippi State in 2010. Favorite things include: Heat Transfer, the New Orleans Saints, and ice cream.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'justin-liddell-pe',
            'status'    => 'draft',
            'order'     => 54,
            'job_title' => 'senior MEP engineer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Justin-Liddell.jpg',
        ),
        array(
            'title'     => 'BRIAN, PE, CEM, LEED AP',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Although the spiders he\'s encountered hiding around mechanical equipment are decidedly not radioactive, Brian is proud to be your friendly neighborhood energy engineer! (Super powers pending)</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'brian-wachholz-eit-cem-leed-ap',
            'status'    => 'publish',
            'order'     => 13,
            'job_title' => 'director of engineering',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Brian-Wachholz-Website.jpg',
        ),
        array(
            'title'     => 'MATT, PE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Matt is a husband, dad, poppa, Christ follower, foodie, espresso snob, and excel nerd with a big heart and a bigger sense of humor who enjoys solving all kinds of problems and optimizing all the things.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'matt-larcom-pe',
            'status'    => 'publish',
            'order'     => 52,
            'job_title' => 'senior project engineer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Matt-LarcomDSC_2693-1.jpg',
        ),
        array(
            'title'     => 'REBEKAH, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Rebekah helps clients maximize their energy conservation efforts. She\'s also an amateur musician and part time explorer.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'rebekah-hansen-cem',
            'status'    => 'private',
            'order'     => 57,
            'job_title' => 'project developer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/R-Hansen.jpg',
        ),
        array(
            'title'     => 'BENJAMIN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Ben loves travel and adventure. Seeing new places or striving to make his clients efficient and happy is all thrilling action in his eyes.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'benjamin-mund',
            'status'    => 'publish',
            'order'     => 44,
            'job_title' => 'business development',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/B-Mund.jpg',
        ),
        array(
            'title'     => 'TRENTON',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Trenton is a proud girl dad with a hands‑on mindset. He enjoys the outdoors, tinkering on vehicles, and tending livestock, and brings that same practical thinking and attention to detail into every project.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'trenton-smith',
            'status'    => 'publish',
            'order'     => 49,
            'job_title' => 'senior MEP engineer',
            'division'  => 'Engineering',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2022/05/Trenton-Smith-600x450-1.jpg',
        ),
        array(
            'title'     => 'JONATHAN, EIT',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Jonathan is an aspiring engineer ready to take on the world. He enjoys spending time with family, working out, and going to the movies.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jonathan-soria-eit',
            'status'    => 'publish',
            'order'     => 56,
            'job_title' => 'project engineer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jonathan-Soria-Resized.jpg',
        ),
        array(
            'title'     => 'RYAN, PE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Ryan enjoys wood-working, welding, and weightlifting. He can also be found teaching differential equations and engineering concepts to his wife and son.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'ryan-hattaway-eit',
            'status'    => 'publish',
            'order'     => 51,
            'job_title' => 'project engineer',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Ryan-Hattaway-Engineering-Intern.jpg',
        ),
        array(
            'title'     => 'PETER',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Pete wants to continue serving his country by making it brighter as a lighting project manager.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'peter-lassen',
            'status'    => 'draft',
            'order'     => 60,
            'job_title' => 'project manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/P-Lassen.jpg',
        ),
        array(
            'title'     => 'MATT',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Matt is a musician and at-home gourmet drawn to anything electrical or mechanical. He loves tapping into his creativity to solve problems.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'matt-riley',
            'status'    => 'publish',
            'order'     => 62,
            'job_title' => 'senior lighting solutions manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/M-Riley.jpg',
        ),
        array(
            'title'     => 'CHARLES',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Chuck loves God, his wife, his kids and his Job in that order. He loves what he does and does what he loves. He loves the challenge of solving a problem, just call him ol\' sparky.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'charles-fisk',
            'status'    => 'draft',
            'order'     => 66,
            'job_title' => 'lighting electrical specialist',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Charles-Fisk-1-of-1-2.jpg',
        ),
        array(
            'title'     => 'DUNCAN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Duncan loves his ever growing car and motorcycle collection, but his true colors show under the LED light that he installed above you!</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'duncan-broach',
            'status'    => 'publish',
            'order'     => 67,
            'job_title' => 'director of information systems',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Web-Resized-1.jpg',
        ),
        array(
            'title'     => 'PATRICK',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Patrick enjoys finding solutions for clients that will save on operating costs. He also spends quite a bit of time watching his daughter compete in gymnastics.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'patrick-hayes',
            'status'    => 'publish',
            'order'     => 70,
            'job_title' => 'senior project manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Patrick-Hayes.png',
        ),
        array(
            'title'     => 'PAUL',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Listening to clients, overachieving their expectations, and gaining their trust is where Paul finds satisfaction. His passion is playing music and his love is his wife and kids.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'paul-cuellar',
            'status'    => 'publish',
            'order'     => 69,
            'job_title' => 'site superintendent',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/P-Cuellar.jpg',
        ),
        array(
            'title'     => 'MIKE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Mike is passionate about hunting, fishing, and 80\'s hairbands, but even Motley Crue can\'t rival the pride he feels making a difference in schools.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'mike-meek',
            'status'    => 'publish',
            'order'     => 61,
            'job_title' => 'project manager and safety manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/M-Meek.jpg',
        ),
        array(
            'title'     => 'JOHNNY',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>When not spending time playing with his two children, Johnny is playing with fire and smoke putting out fires for his clients and smoking BBQ for his family and friends.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'johnny-brewer',
            'status'    => 'publish',
            'order'     => 73,
            'job_title' => 'senior project manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Johnny-Brewer-Website.jpg',
        ),
        array(
            'title'     => 'BEN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>1 wife, 3 children, 2 dogs, a parakeet, and a South Padre hermit crab acquired on vacation. Managing these with ease makes managing projects like a vacation.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'ben-todd',
            'status'    => 'publish',
            'order'     => 71,
            'job_title' => 'senior project manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Ben-Todd-600-x-450.jpg',
        ),
        array(
            'title'     => 'CHRIS',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Chris enjoys the accomplishments of DIY projects, helping clients effectively conserve energy, and spending quality time with his family.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'chris-davis',
            'status'    => 'draft',
            'order'     => 75,
            'job_title' => 'energy systems specialist',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Chris-Davis-600-x-450.jpg',
        ),
        array(
            'title'     => 'TRAVIS WHITE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Travis loves learning and growing with the E3 team. He enjoys spending his free time with friends and family, as well as being in the great outdoors.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'travis-white',
            'status'    => 'draft',
            'order'     => 78,
            'job_title' => 'intern',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Travis-White.jpg',
        ),
        array(
            'title'     => 'DESTINY, CEBS',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Destiny is a care-free, music-loving, crazy pet mom, who lives with intention! She is grateful for each pop of color life brings.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'destiny-hinson',
            'status'    => 'publish',
            'order'     => 21,
            'job_title' => 'director of people operations',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Destiny-Hinson-destiny-250-Edit.jpg',
        ),
        array(
            'title'     => 'EDWARD',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>When he\'s not illuminating projects, he\'s illuminating the lives of his wife and son – a true master of both light fixtures and dad jokes. Balancing watts and tots with style!</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'edward-norman',
            'status'    => 'publish',
            'order'     => 63,
            'job_title' => 'director of lighting strategy',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Edward-Norman-283.jpg',
        ),
        array(
            'title'     => 'EMILY BROACH',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Emily is working hard for the team... and on her bio.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'emily-broach',
            'status'    => 'draft',
            'order'     => 79,
            'job_title' => 'hr intern',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Emily-Broach-261.jpg',
        ),
        array(
            'title'     => 'JAMES',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>James\' favorite 80s TV show catchphrase, "I love it when a plan comes together," embodies his passion for the Lord\'s Plan and his own E-Team\'s triumphs.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'james-harris',
            'status'    => 'publish',
            'order'     => 16,
            'job_title' => 'director of construction, southeast',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/James-Harris-web-1000.jpg',
        ),
        array(
            'title'     => 'BENJAMIN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Ben is working hard to learn the ropes, and on his bio.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'benjamin-hardy',
            'status'    => 'draft',
            'order'     => 83,
            'job_title' => 'intern',
            'division'  => 'Interns',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Benjamin-Hardy-6642_600x450.jpg',
        ),
        array(
            'title'     => 'AMANDA',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Amanda is an adventurer at heart who values her faith and friendships and brings her passion to our team for the summer.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'amanda-white',
            'status'    => 'draft',
            'order'     => 82,
            'job_title' => 'intern',
            'division'  => 'Interns',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Amanda-White-6649_600x450.jpg',
        ),
        array(
            'title'     => 'JONATHAN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Knock knock. Who\'s there? A bio.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'jonathan-fisk',
            'status'    => 'draft',
            'order'     => 80,
            'job_title' => 'lighting specialist intern',
            'division'  => 'Business Administration',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Jonathan-Fisk-600x450-1.jpg',
        ),
        array(
            'title'     => 'DIEGO',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>They say you grow up to be like your parents. Since I\'m working at E3, I guess they were right.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'diego-valls',
            'status'    => 'draft',
            'order'     => 81,
            'job_title' => 'performance management intern',
            'division'  => 'Interns',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Diego-Valls-600-x-450.jpg',
        ),
        array(
            'title'     => 'DAN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Dan loves helping people-especially when he can help make their lives more comfortable! Just don\'t ask him to help you move….he\'s got to draw the line somewhere.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'dan-schmitz',
            'status'    => 'publish',
            'order'     => 40,
            'job_title' => 'business development',
            'division'  => 'Business Development',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Dan-Schmitz-600x450-2.jpg',
        ),
        array(
            'title'     => 'ANDREW',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Andrew loves to help people and loves getting lost in a new city.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'andrew-healthcare',
            'status'    => 'draft',
            'order'     => 39,
            'job_title' => 'business development, healthcare',
            'division'  => 'Business Development',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Andrew-600x450-1.jpg',
        ),
        array(
            'title'     => 'LARRY',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Larry\'s passionate about his customers, 80\'s music, Philadelphia Eagles, and proper baseball swing mechanics.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'larry-jones',
            'status'    => 'publish',
            'order'     => 31,
            'job_title' => 'business development team lead, municipal',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Larry-Jones-600x450-1.jpg',
        ),
        array(
            'title'     => 'TIM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>When Tim\'s not developing energy-saving initiatives, he\'s growing unique heirloom crops or enjoying the great outdoors hunting.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'tim-rowe',
            'status'    => 'publish',
            'order'     => 14,
            'job_title' => 'senior project developer',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Tim-Rowe-600x450-1.jpg',
        ),
        array(
            'title'     => 'KATIA',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Katia is a traveler, foodie, and outdoor enthusiast who brings the same curiosity and energy to work.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'katia-monteros',
            'status'    => 'publish',
            'order'     => 68,
            'job_title' => 'IT data analyst',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Katia-Monteros-600x450-1.jpg',
        ),
        array(
            'title'     => 'PAYTON',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Creative at heart and positive by nature, Payton loves sharing stories, connecting with people, and being outside with her family.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'payton-hubbard',
            'status'    => 'publish',
            'order'     => 9,
            'job_title' => 'marketing and outreach coordinator',
            'division'  => 'Marketing, Communications & Media',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Payton-Hubbard-600x450-2.jpg',
        ),
        array(
            'title'     => 'BRYCE',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>When he\'s not keeping projects on track, Bryce is chasing fish, pickleball volleys, or soccer goals—sometimes all in the same weekend. He brings that same competitive spirit and team mindset to E3 every day.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'bryce-bradish',
            'status'    => 'publish',
            'order'     => 65,
            'job_title' => 'Lighting Solutions Assistant',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Bryce-Bradish-600x450-1-of-1.jpg',
        ),
        array(
            'title'     => 'DREYVAN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Dreyvan enjoys tackling challenges and values teamwork, clear communication, and results that make a difference.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'dreyvan-strickland',
            'status'    => 'publish',
            'order'     => 19,
            'job_title' => 'construction manager',
            'division'  => 'Project Management',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Dreyvan-Strickland-600x450-1-of-1.jpg',
        ),
        array(
            'title'     => 'RICHARD',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Rich loves a good adventure, books on tape, dad jokes, and great Tex-Mex.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'richard-gibbens',
            'status'    => 'publish',
            'order'     => 42,
            'job_title' => 'business development, municipal',
            'division'  => 'Business Development',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Richard-Gibbens-600x450-1.jpg',
        ),
        array(
            'title'     => 'SHERI',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Sheri adopted a manatee, Lucille, who migrates to Florida in winter to repopulate her species. Save the manatees!</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'sheri-wagner',
            'status'    => 'draft',
            'order'     => 23,
            'job_title' => 'people operations partner',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Sheri-Wagner.jpg',
        ),
        array(
            'title'     => 'CURTIS',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Limitless Energy and a Member of Team Happy! ...connecting with people, building great relationships, and enjoying family, fishing, and all the fun!</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'curtis-eldridge',
            'status'    => 'publish',
            'order'     => 45,
            'job_title' => 'business development partner',
            'division'  => 'Business Development',
            'tagline'   => 'Curtis is working hard for his clients, and on a bio.',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Curtis-Eldridge-600x450-1.jpg',
        ),
        array(
            'title'     => 'RON',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Ron connects the dots for his community and cherishes time with family and friends.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'ron-mcvey',
            'status'    => 'publish',
            'order'     => 38,
            'job_title' => 'business development',
            'division'  => 'Business Development',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Ron-McVey-600x450-1.jpg',
        ),
        array(
            'title'     => 'TIM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Tim will talk football with anyone…. and tackle infrastructure solutions for everyone.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'tim-davis',
            'status'    => 'publish',
            'order'     => 43,
            'job_title' => 'business development, municipal',
            'division'  => 'Business Development',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Timothy-Davis-600x450-1.jpg',
        ),
        array(
            'title'     => 'RYDER',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>"Recovering" school superintendent, Ryder loves good jokes and analogies, and his playlist might surprise you for a guy who wears boots and drives a big truck.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'ryder-appleton',
            'status'    => 'publish',
            'order'     => 37,
            'job_title' => 'business development',
            'division'  => 'Business Development',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/01/Ryder-Appleton-600x450-1.jpg',
        ),
        array(
            'title'     => 'TRINI',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Trini builds communities through teaching and organizing dance events and brings that same passion for connection and growth to People Operations.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'trini-johnson',
            'status'    => 'publish',
            'order'     => 22,
            'job_title' => 'people operations coordinator',
            'division'  => 'Business Administration',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/03/Trini-Johnson-600x450-1.jpg',
        ),
        array(
            'title'     => 'SHANE, PE, CEM',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Faith, family, fishing, hunting, spreadsheets, dirt bikes, podcasts, construction, analysis, planning, pack goats (yes, it\'s a thing), mentoring the next generation – and making all of that fun.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'shane-white',
            'status'    => 'publish',
            'order'     => 53,
            'job_title' => 'senior project engineer',
            'division'  => 'Engineering',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/03/Shane-White-600x450-1.jpg',
        ),
        array(
            'title'     => 'SRDAN',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Srdan sees life in cinematic frames… including his embarrassing moments in slow motion.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'srdan-srdenovic',
            'status'    => 'publish',
            'order'     => 8,
            'job_title' => 'sr. content producer',
            'division'  => 'Marketing, Communications & Media',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/04/Srdan-Srdenovic-600x450-1.jpg',
        ),
        array(
            'title'     => 'MARCUS',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Marcus is a K-12 facilities veteran who\'s managed bond programs worth hundreds of millions and a knife collection worth bragging about. He\'s at home in a boardroom, a deer stand, or a school hallway.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'marcus-crispin',
            'status'    => 'publish',
            'order'     => 72,
            'job_title' => 'senior project manager',
            'division'  => 'Executive',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/04/Marcus-Crispin-600x450-1.jpg',
        ),
        array(
            'title'     => 'ALEX',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Alex is working hard for our team, and on a bio.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'alex-davis',
            'status'    => 'publish',
            'order'     => 29,
            'job_title' => 'accounts payable specialist.',
            'division'  => 'Business Administration',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/04/Alexis-Davis-600x450-1.jpg',
        ),
        array(
            'title'     => 'TIFFANY',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Tiffany is working hard for her clients, and on a bio.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'tiffany-forester',
            'status'    => 'publish',
            'order'     => 25,
            'job_title' => 'people operations partner - payroll',
            'division'  => 'Business Administration',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/05/Tiffany-Forester-600x450-1.jpg',
        ),
        array(
            'title'     => 'GEORGIA',
            'content'   => '<!-- wp:paragraph -->' . "\n" . '<p>Georgia is working hard for her clients, and on a bio.</p>' . "\n" . '<!-- /wp:paragraph -->',
            'slug'      => 'georgia-killian',
            'status'    => 'publish',
            'order'     => 59,
            'job_title' => 'engineering intern',
            'division'  => 'Engineering',
            'tagline'   => '',
            'image_url' => 'https://www.e3es.com/wp-content/uploads/2026/06/Georgia-Killian-600x450-1.jpg',
        ),
    );
}
